version: 2.1
orbs:
  terragrunt: getresq/terragrunt@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/

jobs:
  # Create a job to test the commands of your orbs.
  # You may want to add additional validation steps to ensure the commands are working as expected.
  validate-command-sequence-run-all:
    executor: terragrunt/default
    steps:
      - checkout
      - terragrunt/plan-all:
          path: "src/infra"
      - terragrunt/apply-all:
          path: "src/infra"
  validate-command-sequence-individual:
    executor: terragrunt/default
    steps:
      - checkout
      - terragrunt/plan:
          path: "src/infra/environments/testing"
      - terragrunt/apply:
          path: "src/infra/environments/testing"
workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - validate-command-sequence-run-all:
          filters: *filters
      - validate-command-sequence-individual:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: getresq/terragrunt
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - validate-command-sequence-run-all
            - validate-command-sequence-individual
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
