description: >
  A docker-based Terragrunt and Terraform executor using the https://github.com/devops-infra/docker-terragrunt image
docker:
  - image: 'devopsinfra/docker-terragrunt:aws-tf-<<parameters.tf-version>>-tg-<<parameters.tg-version>>'
parameters:
  resource_class:
    default: medium
    description: Specify the resource class for Docker Executor
    type: string
  tf-version:
    default: 1.1.9
    description: >
      Specify the Terraform version to use
      https://hub.docker.com/r/devopsinfra/docker-terragrunt/tags
    type: string
  tg-version:
    default: 0.37.1
    description: >
      Specify the Terragrunt version to use
      https://hub.docker.com/r/devopsinfra/docker-terragrunt/tags
    type: string
resource_class: << parameters.resource_class >>
